// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2ts-5l5YxrzRqrb2Eu06cQrzNAdIoKNQ',
    appId: '1:752739545466:web:1c477a75d4b58c226266c3',
    messagingSenderId: '752739545466',
    projectId: 'zia-connect-airport',
    authDomain: 'zia-connect-airport.firebaseapp.com',
    storageBucket: 'zia-connect-airport.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvUQzdFxaCI-BGEiD0ohbGwKxw-QCxqoA',
    appId: '1:752739545466:android:bfb85f20a4cbceed6266c3',
    messagingSenderId: '752739545466',
    projectId: 'zia-connect-airport',
    storageBucket: 'zia-connect-airport.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRTKRH94H3HA5iBuUdnIG0W06LAZzxNVw',
    appId: '1:752739545466:ios:7345f28ce0d306106266c3',
    messagingSenderId: '752739545466',
    projectId: 'zia-connect-airport',
    storageBucket: 'zia-connect-airport.firebasestorage.app',
    iosBundleId: 'com.example.ziaConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRTKRH94H3HA5iBuUdnIG0W06LAZzxNVw',
    appId: '1:752739545466:ios:7345f28ce0d306106266c3',
    messagingSenderId: '752739545466',
    projectId: 'zia-connect-airport',
    storageBucket: 'zia-connect-airport.firebasestorage.app',
    iosBundleId: 'com.example.ziaConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2ts-5l5YxrzRqrb2Eu06cQrzNAdIoKNQ',
    appId: '1:752739545466:web:f1cfa20370f279486266c3',
    messagingSenderId: '752739545466',
    projectId: 'zia-connect-airport',
    authDomain: 'zia-connect-airport.firebaseapp.com',
    storageBucket: 'zia-connect-airport.firebasestorage.app',
  );
}
